var player;
var aliens;
var bullets;
var bulletTime = 0;
var cursors;
var fireButton;
var explosions;
var starfield;
var score = 0;
var scoreString = '';
var scoreText;
var lives;
var enemyBullet;
var firingTimer = 0;
var stateText;
var livingEnemies = [];
var aliens_moving_left = false;
var alien_velocity = 1;
var xmargin = 0;
var ymargin = 100;
var nextgamestate = '';
var bulletmax = 22;
var bulletmin = 15;
var bulletcount = 0;
var ship = null;
var shipscore = 0;
var aliens_moving = true;

